CREATE TABLE clients (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         client_id VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE balances (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          client_id BIGINT NOT NULL,
                          currency VARCHAR(3) NOT NULL,
                          amount DECIMAL(19, 4) NOT NULL,
                          version BIGINT NOT NULL DEFAULT 0,

                          CONSTRAINT fk_balances_client
                              FOREIGN KEY (client_id)
                                  REFERENCES clients (id),

                          CONSTRAINT uk_balances_client_currency
                              UNIQUE (client_id, currency)
);

CREATE TABLE conversions (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             transaction_id VARCHAR(36) NOT NULL UNIQUE,
                             client_id VARCHAR(50) NOT NULL,
                             source_amount DECIMAL(19, 4) NOT NULL,
                             source_currency VARCHAR(3) NOT NULL,
                             target_amount DECIMAL(19, 4) NOT NULL,
                             target_currency VARCHAR(3) NOT NULL,
                             rate DECIMAL(19, 8) NOT NULL,
                             idempotency_key VARCHAR(100),
                             created_at TIMESTAMP NOT NULL,

                             CONSTRAINT uk_conversions_client_idempotency
                                 UNIQUE (client_id, idempotency_key)
);

INSERT INTO clients (client_id)
VALUES ('CLIENT-001');

INSERT INTO clients (client_id)
VALUES ('CLIENT-002');

INSERT INTO balances (client_id, currency, amount)
SELECT id, 'USD', 10000.0000
FROM clients
WHERE client_id = 'CLIENT-001';

INSERT INTO balances (client_id, currency, amount)
SELECT id, 'EUR', 8000.0000
FROM clients
WHERE client_id = 'CLIENT-001';

INSERT INTO balances (client_id, currency, amount)
SELECT id, 'GBP', 5000.0000
FROM clients
WHERE client_id = 'CLIENT-002';